# Generated by Django 5.2.7 on 2025-11-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
